---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dubbo2istio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: dubbo2istio
  name: dubbo2istio
rules:
  - apiGroups:
      - networking.istio.io
    resources:
      - serviceentries
    verbs:
      - get
      - watch
      - list
      - update
      - patch
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: dubbo2istio
  name: dubbo2istio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dubbo2istio
subjects:
  - kind: ServiceAccount
    name: dubbo2istio
    namespace: dubbo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo2istio
  labels:
    app: dubbo2istio
spec:
  selector:
    matchLabels:
      app: dubbo2istio
  replicas: 1
  template:
    metadata:
      labels:
        app: dubbo2istio
    spec:
      serviceAccountName: dubbo2istio
      containers:
        - name: dubbo2istio
          image: "aeraki/dubbo2istio"
          imagePullPolicy: Always
          env:
            - name: REGISTRY_ADDR
              value: "zookeeper:2181"
            - name: REGISTRY_TYPE
              value: "zookeeper"
