---

name: e2e-nacos

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
    branches:
      - '*'

env:
  ISTIO_VERSION: 1.10.0
  SCRIPTS_DIR: test/e2e/scripts
  COMMON_DIR: test/e2e/common

jobs:
  TestNacos:
    runs-on: ubuntu-16.04
    timeout-minutes: 60
    strategy:
      fail-fast: true
    name: e2e
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
      - name: Install dependencies
        run: |
          go version
          go get golang.org/x/tools/cmd/goimports
      - name: build docker
        run: make docker-build-e2e
      - name: Prepare envrionment
        run: bash ${SCRIPTS_DIR}/pre.sh
      - name: Install Minikube
        run: bash ${SCRIPTS_DIR}/minikube.sh start
      - name: Install aeraki
        run: bash ${SCRIPTS_DIR}/aeraki.sh
      - name: Install Istio
        run: bash ${SCRIPTS_DIR}/istio.sh -y -f ${COMMON_DIR}/istio-config.yaml
      - name: Install dubbo2istio
        run: bash ${SCRIPTS_DIR}/dubbo2istio.sh nacos
      - name: test
        run: go test -v github.com/aeraki-framework/double2istio/test/e2e/nacos/
